version: '3.9'

networks:
  microblog: 

services:
  webnginx:
    image: nginx:latest
    container_name: webnginx
    ports:
      - 43080:80
    volumes:
      - ./src:/var/www/html
      - ./infrastracture/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - database
    networks:
      - microblog

  nodejs:
    build:
      context: .
      dockerfile: ./infrastracture/node/Dockerfile
    container_name: nodejs
    volumes:
      - ./src:/var/www/html
    ports:
      - 43000:3000
    depends_on:
      - backend
    networks:
      - microblog
    command: sh -c "npm install && npm run dev"

  backend:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: ./infrastracture/php/Dockerfile
    container_name: backend
    volumes:
      - ./src:/var/www/html
    ports:
      - 49000:9000
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - microblog

  database:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    tty: true 
    ports:
      - 43306:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    volumes:
      - ./infrastracture/mysql:/var/lib/mysql
    networks:
      - microblog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 43081:80
    environment:
      PMA_HOST: database
    depends_on:
      - database
    networks:
      - microblog
      