name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Setup and run all commands inside ./src
      run: |
        cd ./src &&
        php -r "file_exists('.env') || copy('.env.example', '.env');" &&
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist &&
        php artisan key:generate &&
        chmod -R 777 storage bootstrap/cache &&
        mkdir -p database &&
        touch database/database.sqlite &&
        vendor/bin/phpunit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
