name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: "Setup PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Setup and run all commands inside ./src
      run: |
        cd ./src &&
        php -r "file_exists('.env') || copy('.env.example', '.env');" &&
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist &&
        php artisan key:generate &&
        chmod -R 777 storage bootstrap/cache &&
        mkdir -p database &&
        touch database/database.sqlite &&
        vendor/bin/phpunit
    - uses: php-actions/phpstan@v3
      with:
        path: src/
        configuration: src/phpstan.neon
        memory_limit: 256M
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
